version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - celery
      - celery-beat

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A library_project_final worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A library_project_final beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
