# Generated by Django 5.0.4 on 2024-04-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="actual_return",
            field=models.DateField(blank=True),
        ),
    ]
