# Generated by Django 5.0.4 on 2024-04-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("borrows", "0002_alter_borrow_actual_return"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrow",
            name="actual_return",
            field=models.DateField(blank=True, null=True),
        ),
    ]
